
var DATA = {
	COMPANIES: {
		company0: {
			name: 'BEST',
			icon: '/images/BESTlogo.png',
			description: ['BEST, Board of European Students of Technology, is a constantly growing non-profit and non-political organisation. Since 1989 BEST has been providing communication, cooperation and exchange opportunities for students all over Europe.','96 Local BEST Groups in 33 countries are creating a growing, well-organised, powerful, young and innovative student network. More than 3350 members are involved in the day-to-day development of our services and almost one million students are reached through our events and initiatives.','BEST promotes „Empowered diversity“ and helps European students of technology become more internationally minded, by reaching a better understanding of European cultures and developing the ability to work and volunteer in a global environment. Technical students are given the opportunity through BEST courses and Engineering Competitions to broaden their knowledge in topics which complement their engineering education. This also create the context in which members of the organisation can share knowledge and gain experience by organising these events.','On the other hand, BEST also strives to broaden the job market horizons by giving opportunities through career related events (job fairs, company days, workshops) and an international career center. Last but not least, BEST has developed its own internal training system, to better sustain the organisation; therefore its members have also the opportunity to improve their skills and knowledge by participating in training events.'],
			acceptsCV: true,
			profiles:['']
		},
		company11: {
			name: 'BBVA',
			icon: '',
			description: ['La historia de BBVA es la historia de muchas personas que, desde mediados del siglo XIX, han formado parte de más de un centenar de entidades financieras que se han ido uniendo para ampliar su proyecto empresarial','Hoy, en BBVA trabajamos por un futuro mejor para las personas, buscando relaciones duraderas con nuestros clientes que cambian la forma de ver el negocio. Como resultado de este trabajo, BBVA se ha convertido en todo un referente mundial y en uno de los bancos más reconocidos y premiados.','BBVA apuesta firmemente por el futuro y está siendo pionero en la adaptación a las necesidades que impone un mercado cada vez más global, en definitiva, a la banca del siglo XXI.','Una trayectoria de más de 150 años avala esta apuesta.'],
			profiles: ['Carreras técnicas superiores: Ingenierías, Matemáticas, Estadística, Física, etc','Economía y ADE'],
			link: 'https://careers.bbva.com/espana/',
			hasLink: true,
			acceptsCV: true,
		},
		company12: {
			name: 'B-Lingual',
			icon: '',
			//Quieren el texto con formato!!//
			description: ['Esta señora quiere el texto con formato'],
			profiles:['Estudiantes de últimos cursos con interés en aprender un idioma extrajero'],
			link: 'www.b-lingualexperience.com',
			hasLink: true,
			acceptsCV: false,
		},
		company13: {
			name: 'Carrefour',
			icon: '',
			//Falta poner las negritas en su sitio!//
			description: ['En la actualidad, contamos con más de 470.000 empleados en más de 30 países. Somos la empresa nº 1 de distribución en Europa y nº 2 en el mundo gracias a la pasión y el talento de nuestros empleados.','Somos de origen Francés y estamos presentes en España desde el año 1973, donde 40.000 personas componemos Carrefour y gestionamos 173 hipermercados, 115 supermercados y 114 tiendas de proximidad. Además, Carrefour cuenta con las líneas de negocio: Finanzas y Seguros, gasolineras, viajes, Carrefour móvil y entradas.','Nuestra ambición es seguir siendo el comerciante favorito ¿Cómo lo conseguimos?','Siendo innovadores ofreciendo nuevo productos, apostando por la diversidad de formatos de tienda, incorporando nuevos servicios y para mejorar la vida de nuestros clientes.'],
			profiles:['Ingenieros Agrónomos y Agrícolas','Ingenieros de Telecomunicaciones','Ingenieros Industriales'],
			link: 'http://www.carrefour.es/trabaja-en- carrefour/mas-info/',
			hasLink: true,
			acceptsCV: true,
		},
		company14: {
			name: 'OVB Allfinanz España, S.A.',
			icon: '/images/OVB_logo.png',
			description: ['OVB, compañía líder en asesoramiento financiero en Europa. Desde su fundación en 1970 en Colonia, Alemania, hasta el día de hoy, nuestra preocupación por los objetivos y necesidades de nuestros clientes, nos ha llevado a 14 países en Europa, entre ellos España en 2003','El grupo OVB cotiza en la Bolsa de Frankfurt desde Julio de 2006 y colabora con más de 150 entidades de gran renombre y alta competitividad en el sector financiero y asegurador, tanto a nivel nacional como internacional.','OVB Allfinanz España trabaja, como en el resto de Europa, con el método A-A-S (Análisis, Asesoramiento y Servicio) que se orienta en las fases de la vida, considerando los factores que influyen como la edad, el entorno profesional y social, las prioridades y deseos de cada uno.','Tanto los objetivos a corto como a largo plazo se tienen en cuenta en nuestro modelo de asesoramiento de manera que realmente sea posible planificar eficazmente el futuro y acompañar al cliente prestando nuestro servicio a lo largo de toda la vida.','OVB Allfinanz España no tiene productos propios, por tanto nuestro asesoramiento es independiente y personalizado para el cliente con un servicio dinámico y continuo.','Nuestros 3 millones de clientes agradecen haber encontrado en el asesoramiento multitemático de OVB un servicio individualizado que les da respuesta a todas sus cuestiones y dudas financieras.','El asesoramiento multitemático de OVB Allfinanz España se divide en las siguientes fases:','<ul><li>Protección personal y de ingresos, asegurando que nuestro cliente siempre alcance sus objetivos.</li>','<li>Protección del patrimonio, garantizando la seguridad del mismo.</li>','<li>Protección del patrimonio, garantizando la seguridad del mismo.</li>','<li>Creación del patrimonio, destinado a construir un patrimonio para la jubilación.</li>','<li>Crecimiento del patrimonio, optimizando la elección de nuestro cliente.</li></ul>','El cumplimiento de todas las fases del asesoramiento multitemático de OVB Allfinanz España tendrá como resultado una correcta planificación financiera para nuestro cliente.','Visítanos en:'],
			link:'www.ovb.es',
			hasLink: true,
			acceptsCV: true,
		},
		company15: {
			name: 'Page Personnel',
			icon: '/images/pagepersonnel_logo.jpg',
			description: ['Page Personnel, perteneciente a PageGroup, es la consultora líder en selección y trabajo temporal especializado. Identificamos y seleccionamos perfiles intermedios y personal de apoyo cualificado para posiciones temporales e indefinidas a través de nuestros consultores especializados. Nuestra misión es satisfacer las necesidades de selección de nuestros clientes y ayudar en el desarrollo profesional de nuestros candidatos.','Estamos especializados en 15 áreas, entre ellas destacamos Tecnologías de la información e Ingenieros y Técnicos. Los perfiles más habituales que cubrimos en el área tecnológica son:',' <li>Desarrolladores</li> <li>Jefaturas de Proyecto</li><li>Administradores de sistemas</li><li>Expertos en BBDD</li>','Dentro del área ingenieril, nuestros posiciones suelen ser:','<li>Supply Chain: Logística, compras y almacén</li><li>Oficina Técnica: Estudios, presupuestos, I+D y proyectos</li><li>Procesos: Mantenimiento, calidad y producción</li>','Visítanos en:'],
			link:'www.pagepersonnel.es',
			video:'https://www.youtube.com/watch?v=itCyUfV4EiA',
			hasLink: true,
			acceptsCV: true,
		},
		company16: {
			name: 'Profco - Mediación de personal de enfermería para trabajar en Alemania.',
			icon: '/images/profco_logo.png',
			description: ['Profco es la agencia de mediación personal en la atención sanitaria. Nuestra tarea es integrar profesionales de enfermería graduados españoles en empresas alemanas en el sector de hospitales, clínicas, residencias geriátricas y otras instituciones. Hemos desarrollado un concepto totalmente nuevo que ha sido estudiado y examinado con detenimiento por la Red EURES (European Employment Service) y otras instituciones como por ejemplo la Red iQ de Alemania.','Nuestro proyecto incluye sin coste alguno para los candidatos:','<ul><li>Preparación hasta alcanzar el nivel requerido de alemán (B2 – de acuerdo con el marco europeo de referencia).</li>','<li>Gestiones necesarias para la homologación del título.</li>','<li>Mediación, acompañamiento y supervisión para formalizar el contrato de trabajo entre la empresa (hospital, clínica, residencia, etc.) y el trabajador (enfermero/a).</li>','<li>Ayuda para encontrar vivienda en Alemania.</li>','<li>Asistencia y apoyo después de la incorporación al puesto de trabajo.</li></ul>','Requisitos mínimos:','<ul><li>Título de enfermería.</li>','<li>Los/as solicitantes deben aportar comprobantes de seguros españoles que tengan una validez de tres meses después de su llegada a Alemania (en particular seguro médico, de accidentes y de responsabilidad civil).</li>','<li>Comprensión y la habilidad para adaptarse a otras personas','-Responsabilidad y aptitud para el trabajo en equipo.</li></ul>','Procedimiento:','<ul><li>Selección de candidatos por profesionales de profco.</li>','<li>Curso intensivo de alemán hasta alcanzar el nivel B2 (en España y Alemania).</li>','<li>Entrevistas de trabajo con posibles empleadores.</li>','<li>Acompañamiento constante hasta firmar el contrato y después apoyo durante 2 años por un gestor de proyecto que habla español</li>','<li>Apoyo para resolver diversos trámites burocráticos (dar de alta el domicilio, solicitar tarjeta fiscal, abrir una cuenta bancaria, dar de alta un vehículo, contratar una línea de Internet y teléfono, etc.)</li>','<li>Asistencia durante el proceso de incorporación</li></ul>','Franja salarial:','<ul><li>A partir de 30.000€ en clínicas y residencias geriátricas.</li></ul>','Con profco de la mano, la integración es más fácil.','Visítanos en:'],
			link:'www.profco.de',
			hasLink: true,
			acceptsCV: true,
		},
		company17: {
			name: 'RSI y Nessa Global Banking Solutions (Grupo Caja Rural)',
			icon: '/images/rsi_logo.jpg',
			description: ['Desde 1987 RSI ha sido gran referente de la tecnología bancaria. RSI nace de la innovación y de la actualidad tecnológica con el fin de dar el mejor servicio a las entidades financieras que confían en nosotros: tanto en nuestro equipo como en nuestras aplicaciones. Hoy en día este panorama tecnológico se instala en el sector bancario a través de nuevas metodologías como e-baking o banca digital y la necesidad de nuestras soluciones cada día son más demandadas en el sector.  La calidad, el trabajo en equipo, así como la formación constante son los pilares de nuestro negocio. El valor fresco, joven y dinámico es el motor de nuestra experiencia y sobre todo son requisitos esenciales para RSI. Necesitamos tu empuje y vivacidad. RSI quiere ser el comienzo de tu trayectoria profesional.',' Déjanos tu CV en nuestro stand o escríbenos a <a href="mailto:rrhh_rsi@cajarural.com">rrhh_rsi@cajarural.com</a>','Visítanos en:'],
			link:'http://www.ruralserviciosinformaticos.com/',
			hasLink: true,
			acceptsCV: true,
		},
		company18: {
			name: 'RÜCKER LYPSA, SLU ( EDAG Group )',
			icon: '/images/rueckerlypsa_logo.jpg',
			description: ['DESCRIPCIÓN:','As a leading global independent engineering partner for the international mobility industry, the EDAG Group, to which the Rücker Lypsa have also belonged since the beginning of the year 2014, develops ready-for-production solutions for automotive future. The industry focus is on the automotive and commercial vehicle industry.','The development of vehicles, derivates, modules and production plant is part of the service portfolio. The EDAG Group is organised into the lines of business Vehicle Engineering, Production Solutions and Electric/Electronics. Vehicle Engineering offers global engineering services and know-how along the entire automotive development process focusing on the manufacturers and suppliers of the automotive industry. The service portfolio covers the key aspects of vehicle development and ranges from styling, form-finding and modelling through package, body and interior/exterior design development to the entire functional integration of systems into the vehicle.','Production Solutions deals with the development of production facilities and factory concepts. The focus is on factory, process and plant development as well as automation engineering and product cost management.','<b>Rücker Lypsa S.L.U.</b>( currently employing more tan 500 professionals ) is the center of competence for styling, design and models of the whole group and is also leader in the Spanish market in design, engineering in powertrain, body and trim development as well as electric / electronic development ( vehicle electric/electronics, comfort and body electronics, driver assistance and safety systems, infotainment and telematics systems as well as electric/electronic system ).','Visit us in:'],
			link:'www.rueckerlypsa.es',
			hasLink: true,
			acceptsCV: true,

		},
		company19: {
			name: 'SCHNEIDER ELECTRIC',
			icon: '/images/schneider_logo.png',
			description: ['DESCRIPCIÓN:','Schneider Electric, como especialista global en gestión de la energía y con operaciones en más de 100 países, ofrece soluciones integrales para diferentes segmentos de mercado, ostentando posiciones de liderazgo en energía e infraestructuras, industria, edificios y centros de datos, así como una amplia presencia en el sector residencial. ','Hoy los más de 170.000 trabajadores de Schneider, gracias a su experiencia ofrecen soluciones innovadoras a nuestros clientes en más de 100 países. Gracias a nuestro programa de acceso a la energía, hemos hecho posible que 2,4 millones de personas dispongan de energía. Es lo que denominamos LIFE IS ON.','Ofrecemos la oportunidad de adherirse a una Compañía internacional, dinámica y responsable que promueve el desarrollo de toda su gente y comunidades de todo el mundo. Siempre fomentando la diversidad e inclusión.','Los valores son el fundamento más sólido para garantizar el éxito a largo plazo de las compañías y favorecer una cultura abierta, de confianza mutua y sostenible. Creemos que una compañía con fuertes valores puede marcar la diferencia en nuestra sociedad.','En Schneider Electric queremos marcar la diferencia todos y cada uno de los días. Por eso trabajamos para que nuestros 8 principios hagan de Schneider Electric una gran compañía.','Visítanos en:'],
			link:'http://www.schneider-electric.es/es/',
			video:'https://www.youtube.com/watch?v=5F17ixk2UUQ',
			hasLink: true,
			acceptsCV: true,
		},
		company20: {
			name: 'ESIC',
			icon: '/images/esic.png',
			description: ['ESIC Business & Marketing School, fundada en el año 1965 por la institución religiosa de los Sacerdotes del Corazón de Jesús (Padres Reparadores), es la Escuela de Negocios líder en la formación en Empresa y Marketing en España gracias a su alto grado de especialización.','ESIC responde a las necesidades de la empresa y de su entorno competitivo formando profesionales capaces de analizar, reflexionar, decidir y actuar responsablemente en todas las áreas de la empresa, en cualquier nivel jerárquico y en cualquier ámbito geográfico, gracias a los programas, que en constante evolución ofrece en marketing, dirección empresarial, comunicación, recursos humanos, finanzas, entornos digitales, comercio internacional, investigación de mercados, etc.','ESIC está presente en 9 ciudades de la geografía española: Madrid, Valencia, Barcelona, Navarra, Zaragoza, Bilbao, Sevilla, Málaga y Granada. También dispone de dos centros en Brasil, uno en la ciudad de Curitiba y otro en Brusque. Tiene firmados importantes acuerdos y convenios de colaboración con entidades y organismos nacionales e internacionales, tanto nivel académico como institucional, que contemplan intercambios de alumnos y profesores. Cuenta con 5 áreas: ','Área de Grado Grados Oficiales, Privados y Dobles Titulaciones.','Área de Postgrado conprogramas MBA (junior, executive y en inglés), másteres especializados, universitarios y programas superiores.','Área Executivecon abiertos para directivos y formación a medida para empresas. ','ESIC Editorial con un fondo editorial que ofrece a estudiantes y profesionales libros, manuales y publicaciones sobre investigación y divulgación de todos los temas relacionados con la empresa','ESIC Idiomas formación en lenguas extranjeras.'],
			acceptsCV: true,
		},
		company21: {
			name: 'everis',
			icon: '/images/everis.png',
			description: ['everis an NTT DATA Company es una consultora multinacional que ofrece soluciones de negocio, estrategia, desarrollo y mantenimiento de aplicaciones tecnológicas, y outsourcing. La compañía, que desarrolla su actividad en los sectores de telecomunicaciones, entidades financieras, industria, utilities, energía, administración pública y sanidad, alcanzó una facturación de 605 millones de euros en el último ejercicio fiscal. En la actualidad, cuenta con 10.600 profesionales distribuidos en sus oficinas y centros de alto rendimiento en 13 países. ','La consultora pertenece al grupo NTT DATA, la sexta compañía de servicios IT del mundo, con 70.000 profesionales y presencia en Asia-Pacífico, Oriente Medio, Europa, Latinoamérica y Norteamérica. La integración enNTT DATApermite a everis ampliar las soluciones y servicios para sus clientes, aumenta sus capacidades, recursos tecnológicos, geográficos y financieros y le ayuda a dar las respuestas más innovadoras a sus clientes… … y sobre todo más talento y nuevas oportunidades. Somos más grandes. Somos más globales. Somos más everis.'],
			acceptsCV: true,
		},
		company22: {
			name: 'Fundación Universidad - Empresa',
			icon: '/images/fue.png',
			description: ['La Fundación Universidad–Empresa es una institución sin ánimo de lucro que aúna a las diecisiete Universidades públicas y privadas con sede en la Comunidad de Madrid y a las empresas madrileñas, a través de la Cámara Oficial de Comercio e Industria. ','Si a lo largo de nuestra trayectoria nos hemos preocupado siempre, y de manera muy especial, por poner en marcha programas y acciones que faciliten la incorporación efectiva de los universitarios al mercado laboral, la actual situación de desempleo nos ha llevado a trabajar con más intensidad en todo lo relacionado con el empleo y la empleabilidad de los jóvenes. ','Y lo hemos hecho partiendo de lo que llamamos DEEP LINKING: escuchando y entendiendo las necesidades reales de los jóvenes, de las empresas y de las universidades, para poder proponer las soluciones más adecuadas y efectivas.'],
			acceptsCV: true,
		},
		company23: {
			name: 'Ibermática',
			icon: '/images/ibermatica.png',
			description: ['Con más de 40 años de actividad en el sector de las TIC, Ibermática impulsa un proyecto empresarial comprometido con el desarrollo social, la innovación y la competitividad. Actualmente agrupa a más de 3.000 profesionales y representa un volumen de negocio próximo a los 230 millones de euros. Dispone de 25 centros operativos repartidos en los mercados de España, Portugal, Andorra, Argentina, Brasil, Chile, Colombia, México, Perú y Estados Unidos. Su trayectoria empresarial se ha caracterizado siempre por una reconocida solvencia financiera y solidez accionarial. Sus principales accionista son: ProA Capital, KutxaBank, O.N.C.E. y el equipo directivo. Nuestro compromiso con la calidad y la eficiencia nos impulsa a la búsqueda permanente de la excelencia. La actividad que desarrollamos se caracteriza por su bajo impacto medioambiental; a pesar de ello, la sostenibilidad es una de nuestras preocupaciones a la hora de organizar y diseñar nuestros procesos.'],
			acceptsCV: true,
		},
		company24: {
			name: 'KIC InnoEnergy',
			icon: '/images/kic.png',
			description: ['KIC InnoEnergy Master School is a joint programme coordinated by eleven leading technical universities and two top European business schools. Our seven master programmes in sustainable energy engineering are carefully designed to provide our students with a unique combination of technical and entrepreneurial skills.','If you are driven by a ‘can do attitude’ and you are passionate about energy, innovation and entrepreneurship, the KIC InnoEnergy Master School will transform your talent into new technologies and ventures.','Be ready to enter an international community of experts coming from all parts of the energy sector and to pursue not just a career, but as a life changing experience that will allow you to make an impact on the future of sustainable energy.','Discover all the opportunities offered by our European Master School: ','§  Focus on sustainable energy engineering ','§  Double degree from top-ranked technical universities','§  Entrepreneurship training at top European business schools','§  Join a European community that goes well beyond education','§  Scholarship opportunities for top applicants'],
			acceptsCV: true,
		},
		company25: {
			name: 'KPMG',
			icon: '/images/kpmg.png',
			description: ['¿Eres de la generación KPMG?','Si quieres averiguarlo, sigue leyendo.','No te vamos a contar aquí que hacemos, ni quiénes somos, ni que servicios prestamos, ni los mercados en que operamos, ni quienes son nuestros principales clientes, ni nuestro enfoque sectorial, ni nuestros programas internacionales, ni nuestra red global, ni siquiera cuantos empleados somos,  ni los programas de talento, formación y desarrollo que podemos ofrecerte, ni nuestro enfoque multidisciplinar, ni nuestra responsabilidad corporativa…','¿Por qué no? Porque todo eso lo tienes al alcance de la mano, a un solo click.','Las organizaciones las hacen las personasque trabajan en ellas. Y de eso es de lo que te queremos hablar, de los profesionales que formamos KPMG. Ese es nuestro valor añadido. El talento, el conocimiento, el compromiso, la inquietud, la creatividad y la capacidad de innovación de las personas que día a día en KPMG hacemos posible que las grandes compañías encuentren respuesta a sus necesidades. ','Las personas son la clave de nuestro éxito y los jóvenes son el futuro de nuestra firma y los principales actores del cambio que está viviendo el mundo. Por eso cada año apostamos por incorporar jóvenes que reúnan esas características que nos hacen diferentes, por las que nuestros clientes depositan su confianza en nosotros, para que rodeados de los profesionales que ya formamos KPMG crezcan, aprendan y se reinventen cada día. ','¿Y cuáles son esas características? Personas con talento conscientes de que el talento también requiere dedicación y esfuerzo para alcanzar sus objetivos; personas capaces de trabajar sus propias habilidades para mejorar día a día; personas que quieran seguir aprendiendo, creciendo y asumiendo retos; personas que sepan aprovechar las oportunidades al máximo y que sepan hasta donde quieren llegar. Porque en KPMG, el limite te lo pones tú. ','Te invitamos a que nos conozcas y tengas la oportunidad de ver cómo somos los profesionales que hacemos posible el reto de seguir siendo una de las empresas más valoradas para trabajar. ','PORQUE COMPARTIMOS VALORES Y FUTURO. Te esperamos.'],
			acceptsCV: true,
		},
		company26: {
			name: 'Oficina Española de Patentes y Marcas',
			icon: '/images/oepm.png',
			description: ['La Oficina Española de Patentes y Marcas (OEPM) es un Organismo Autónomo del Ministerio de Industria, Energía y Turismo que impulsa y apoya el desarrollo tecnológico y económico otorgando protección jurídica a las distintas modalidades de propiedad industrial mediante la concesión de patentes y modelos de utilidad (invenciones); diseños industriales (creaciones de forma); marcas y nombres comerciales (signos distintivos) y títulos de protección de las topografías de productos semiconductores. Asimismo, difunde la información relativa a las diferentes formas de protección de la propiedad industrial.'],
			acceptsCV: true,
		},
		company27: {
			name: 'Orange',
			icon: '/images/orange.png',
			description: ['España es el segundo mercado del grupo Orange, uno de los principales operadores de telecomunicaciones del mundo con más de 231 millones de clientes.','En España somos el operador alternativo de referencia y uno de los principales inversores extranjeros en la industria de telecomunicaciones, con más de 15.000 millones de euros de inversión acumulada.','Más de 13,7 millones de clientes (12.238.000 de telefonía móvil y 1.512.000 de banda ancha fija) confían en nosotros.'],
			acceptsCV: true,
		},
		company28: {
			name: 'PwC',
			icon: '/images/pwc.png',
			description: ['Actividad:',' Somos la mayor firma de servicios profesionales en el mundo, ofrecemos las soluciones que actualmente demandan las empresas ante los riesgos, retos y oportunidades que plantea la globalización de la economía mundial. En España, 4000 profesionales desarrollan su actividad en todas las áreas de negocio a través de una amplia red de oficinas que cubre todo el territorio nacional. ','Las principales líneas de negocio en las que trabajamos son:','Auditoria: El servicio de auditoria financiera está diseñado para ofrecer valor añadido al cliente y no se limita a emitir una opinión sobre las cuentas anuales de la empresa. Este valor añadido es diferencial y se caracteriza por: ','-  La realización de auditorías enfocadas al negocio. ','- La evaluación de la integración de los sistemas y procesos y de la idoneidad de los controles clave, realizando siempre un informe de control interno que identifica las deficiencias. ','- Una metodología de auditoría estandarizada y adaptada a las necesidades de empresas de diversos tamaños y actividad, con los objetivos de eficiencia y calidad. PwC ha obtenido el certificado de calidad ISO 9002 de AENOR para la actividad de auditoría de cuentas. ','Consultoría de Negocio: La división de Consultoría de Negocio de PwC ayuda a sus clientes, empresas y entidades públicas y privadas a conseguir y mantener mejoras de su rendimiento mediante el reforzamiento de la eficacia y eficiencia de sus procesos clave de negocio a lo largo del ciclo de vida de la compañía. Todo ello con un enfoque plenamente sectorial.','Asesoramiento Fiscal y Legal: PwC Tax & Legal Services agrupa en España a un equipo multidisciplinar de 900 abogados y asesores fiscales que forman parte de PwC, la mayor firma de servicios profesionales del mundo. PwC Tax & Legal Services se identifica en el mercado internacional por unas notas específicas que definen su liderazgo. Estas señas de identidad, que a su vez representan sus ventajas competitivas, pueden sintetizarse en los siguientes puntos: ','- Red internacional. ','- Equipos multidisciplinares ','- Especialización técnica y sectorial. ','- Apuesta por el middle-market y la empresa familiar. ','- Asesoramiento jurídico-tributario global e internacional. ','- Perspectiva deontológica. ','- Desarrollo online. ','Implantación geográfica: Tenemos una amplia red de oficinas, con un total de 20, con presencia en todo el territorio nacional: Alicante, Barcelona, Bilbao, La Coruña, Las Palmas, Logroño, Madrid, Málaga, Murcia, Oviedo, Palma de Mallorca, Pamplona, San Sebastián, Santa Cruz de Tenerife, Santander, Sevilla, Valencia, Vigo, Vitoria y Zaragoza.','Para participar en los procesos de selección es imprescindible inscribirse en nuestra Jobsite. Se puede acceder a través de www.pwc.es (apartado Jobsite) o desde https://jobsite.pwc.es','El proceso de selección de recién titulados es continuo durante el año y la incorporación de estos perfiles tiene lugar en el mes de Septiembre. Los procesos de beca son continuos durante todo el año en función de las necesidades de Negocio.'],
			acceptsCV: true,
		},
		company29: {
			name: 'Banco Sabadell',
			icon: '/images/sabadell.png',
			description: ['Un proyecto de futuro en Banco Sabadell','Banco Sabadell es hoy la cuarta entidad financiera más importante del país. Una entidad que en su larga y exitosa trayectoria ha sabido combinar la tradición en la forma de hacer banca, la visión a largo plazo, el crecimiento y la innovación. Banco Sabadell tiene por delante un futuro retador, con un gran proyecto a largo plazo que contempla la transformación del propio negocio, la innovación y la expansión internacional, lo que se traduce en un amplio abanico de oportunidades y nuevos desafíos.','Nuestro programa de becas está diseñado para proporcionar experiencia práctica a los estudiantes.','Calendario','	• Periodo de solicitud: Septiembre/Octubre','	• Periodo de beca: Enero – Junio (500h)','Requisitos','	• Haber superado 50% créditos ó estar cursando estudio de posgrado/máster','	• Expediente académico','	• Inglés fluído','Convenio con principales Universidades y Escuelas de Negocio','Estudiantes de último curso y/o graduados en :','-Grado en Economía','-Grado en Administración de Empresas','-Grado en Estadística','-Grado en Derecho','-Grado en Física','-Grado en Informática','-Grado en Matemáticas ','-Ingeniería (Organización Industrial)','-Ingeniería en Electrónica','-Ingeniería en Telecomunicaciones ','-Inglés: Nivel C1 / C2','-Herramientas Office: Nivel avanzado','Se valorará Formación complementaria en: ','-Banca','-Finanzas','-Instrumentos Financieros','-Matemáticas para los Instrumentos Financieros','-MBA','-Postgrado Técnicas Cuantitativas para los Mercados Financieros'],
			acceptsCV: true,
		},
		company30: {
			name: 'Tecnocom',
			icon: '/images/tecnocom.png',
			description: ['Tecnocom es una multinacional española que cotiza en la Bolsa de Madrid desde 1987. En 2006, Tecnocom inició un proceso Corporativo de expansión con el objetivo de llegar a ser líder en el mercado de la tecnología de la información español.','Tecnocom es una de las tres primeras empresas del sector de la tecnología de la información en España (alrededor de 400 millones de euros de ingresos) con una amplia experiencia en operaciones de elevado nivel tecnológico, como medios de pago bancarios o sistemas de automatización.','Esto hace que Tecnocom tenga una amplia oferta tecnológica y de soluciones de negocio (AMS, IMS, Consultoría de Negocio, BPO, Outsourcing, Servicios gestionados, Redes y la Integración de Sistemas) que cubre todos los sectores de ámbito público y Privado (Banca, Seguros, Industria, Telecomunicaciones, Media y Utilities y la Administración Pública).','Los valores que guían la forma de actuar de Tecnocom están basados en:',' 	Orientación al cliente: Centramos nuestro esfuerzo en la satisfacción del cliente, aportando soluciones innovadoras y un soporte técnico sobresaliente.',' 	Compromiso con la innovación: Promovemos la mejora continua y la innovación para alcanzar la máxima calidad desde criterios de rentabilidad y eficiencia.',' 	Compromiso con nuestros accionistas.',' 	Sostenibilidad: Desarrollamos nuestro negocio con un horizonte estratégico que trasciende los intereses económicos inmediatos, contribuyendo al desarrollo económico, medioambiental y social, tanto a corto como a largo plazo.',' 	Compromiso social: Mantenemos un firme compromiso con la defensa de un uso eficiente de Internet, haciendo especial hincapié en los colectivos de riesgos (menores).',' 	Personas: Captamos los mejores talentos y aseguramos oportunidades de desarrollo en base al mérito y a la aportación profesional.'],
			acceptsCV: true,
		},
	},
	SCHOOLS: {
		etsi_aeronautica_y_del_espacio : 'ETSI Aeronaútica y del Espacio',
    etsi_montes_forestal_y_del_medio_natural : 'ETSI Montes, Forestal y del Medio Natural',
    ets_de_arquitectura : 'ETS de Arquitectura',
    etsi_aeronauticos : 'ETSI Aeronáuticos',
    etsi_agronomos : 'ETSI Agrónomos',
    etsi_caminos_canales_y_puertos : 'ETSI Caminos, Canales y Puertos',
    etsi_montes : 'ETSI Montes',
    etsi_navales : 'ETSI Navales',
    etsi_telecomunicacion : 'ETSI Telecomunicación',
    facultad_de_ciencias_de_la_actividad_fisica_y_del_deporte_inef : 'Facultad de Ciencias de la Actividad Física y del Deporte (INEF)',
    ets_de_edificacion : 'ETS de Edificación',
    euit_aeronautica : 'EUIT Aeronáutica',
    euit_agricola : 'EUIT Agrícola',
    euit_forestal : 'EUIT Forestal',
    centro_de_investigacion_del_transporte_transyt : 'Centro de Investigación del Transporte (TRANSyT)',
    centro_de_estudios_e_inv_para_la_gestion_de_riesgos_agrarios_y_medioamb : 'Centro de Estudios e Inv. para la Gestión de Riesgos Agrarios y Medioamb.',
    instituto_de_sistemas_optoelectronicos_y_microtecnologia : 'Instituto de Sistemas Optoelectrónicos y Microtecnología',
    instituto_de_energia_solar : 'Instituto de Energía Solar',
    instituto_de_ciencias_de_la_educacion_ice : 'Instituto de Ciencias de la Educación (ICE)',
    centro_de_materiales_y_dispositivos_avanzados_para_tic_cemdatic : 'Centro de Materiales y Dispositivos Avanzados para TIC (CEMDATIC)',
    etsi_industriales : 'ETSI Industriales',
    etsi_de_minas_y_energia : 'ETSI de Minas y Energía',
    etsi_diseno_industrial : 'ETSI Diseño Industrial',
    etsi_civil : 'ETSI Civil',
    centro_de_electronica_industrial_cei : 'Centro de Electrónica Industrial (CEI)',
    instituto_de_fusion_nuclear : 'Instituto de Fusión Nuclear',
    centro_de_automatica_y_robotica_car_centro_mixto_upm_csic : 'Centro de Automática y Robótica (CAR). Centro Mixto UPM-CSIC',
    ets_de_ingenieros_informaticos : 'ETS de Ingenieros Informáticos',
    centro_domotica_integral_cedint : 'Centro domótica Integral (CEDINT)',
    centro_de_inv_en_biotecnologia_y_genomica_de_plantas_cbgp : 'Centro de Inv. en Biotecnología y Genómica de Plantas (CBGP)',
    insituto_de_microgravedad_ignacio_da_riva : 'Insituto de Microgravedad "Ignacio Da Riva"',
    e_usoc : 'E-USOC',
    cesvima : 'CESVIMA',
    etsi_en_topografia_geodesia_y_cartografia : 'ETSI en Topografía, Geodesia y Cartografía',
    etsi_de_sistemas_informaticos : 'ETSI de Sistemas Informáticos',
    etsi_y_sistemas_de_telecomunicacion : 'ETSI y Sistemas de Telecomunicación',
    centro_laser : 'Centro Láser',
    instituto_de_investigacion_del_automovil : 'Instituto de Investigación del Automóvil',
    centro_de_investigacion_en_tecnologias_del_sw_y_sist_multimedia_citsem : 'Centro de Investigación en Tecnologías del SW y Sist. Multimedia (CITSEM)',
    centro_superior_de_diseno_de_moda_de_madrid : 'Centro Superior de Diseño de Moda de Madrid',
    facultad_de_bellas_artes : 'Facultad de Bellas Artes',
    facultad_de_ciencias_biologicas : 'Facultad de Ciencias Biológicas',
    facultad_de_ciencias_de_la_documentacion : 'Facultad de Ciencias de la Documentación',
    facultad_de_ciencias_de_la_informacion : 'Facultad de Ciencias de la Información',
    facultad_de_ciencias_economicas_y_empresariales : 'Facultad de Ciencias Económicas y Empresariales',
    facultad_de_ciencias_fisicas : 'Facultad de Ciencias Físicas',
    facultad_de_ciencias_geologicas : 'Facultad de Ciencias Geológicas',
    facultad_de_ciencias_matematicas : 'Facultad de Ciencias Matemáticas',
    facultad_de_ciencias_politicas_y_sociologia : 'Facultad de Ciencias Políticas y Sociología',
    facultad_de_ciencias_quimicas : 'Facultad de Ciencias Químicas',
    facultad_de_comercio_y_turismo : 'Facultad de Comercio y Turismo',
    facultad_de_derecho : 'Facultad de Derecho',
    facultad_de_educacion_centro_de_formacion_del_profesorado : 'Facultad de Educación - Centro de Formación del Profesorado',
    facultad_de_enfermeria_fisioterapia_y_podologia : 'Facultad de Enfermería, Fisioterapia y Podología',
    facultad_de_estudios_estadisticos : 'Facultad de Estudios Estadísticos',
    facultad_de_farmacia : 'Facultad de Farmacia',
    facultad_de_filologia : 'Facultad de Filología',
    facultad_de_filosofia : 'Facultad de Filosofía',
    facultad_de_geografia_e_historia : 'Facultad de Geografía e Historia',
    facultad_de_informatica : 'Facultad de Informática',
    facultad_de_medicina : 'Facultad de Medicina',
    facultad_de_odontologia : 'Facultad de Odontología',
    facultad_de_optica_y_optometria : 'Facultad de óptica y Optometría',
    facultad_de_psicologia : 'Facultad de Psicología',
    facultad_de_trabajo_social : 'Facultad de Trabajo Social',
    facultad_de_veterinaria : 'Facultad de Veterinaria',
    otros_centros : 'Otros Centros',
	}
};
$(document).ready(function(){
	// the "href" attribute of .modal-trigger must specify the modal ID that wants to be triggered
	$('.modal-trigger').leanModal();
});
