
var DATA = {
	COMPANIES: {
		company0: {
			name: 'BEST',
			icon: '/images/BESTlogo.png',
			description: ['<b>BEST</b>, Board of European Students of Technology, es una organización apolítica y sin ánimo de lucro en constante crecimiento. Desde 1989 BEST ha proporcionado oportunidades de comunicación, cooperación e intercambio a estudiantes de toda Europa.','96 grupos locales a lo largo de 33 países conforman una red de estudiantes organizada, fuerte e innovadora. Más de 3350 miembros forman parte día a día del desarrollo de nuestros servicios y más de 1.300.000 estudiantes tienen acceso a nuestros eventos e iniciativas.','BEST promueve la diversidad y las oportunidades, y ayuda a los estudiantes europeos a conseguir una mentalidad abierta internacionalmente mediante un mejor conocimiento de las culturas europeas y desarrollando capacidades de <b>trabajo en un ambiente internacional</b>. Los estudiantes de tecnología tienen la oportunidad de expandir sus conocimientos y formación complementaria mediante cursos y competiciones de ingeniería. Todo esto crea un contexto en el que los miembros de la organización comparten conocimiento y experiencia en la organización de varios tipos de proyectos y eventos.','Por otra parte, en BEST también trabajamos activamente en expandir las oportunidades laborales de los estudiantes europeos mediante eventos como este mismo Forum BEST Madrid, ferias de trabajo internacionales, workshops, y una <b>bolsa de empleo</b> que permite el acceso a las ofertas de nuestros colaboradores y a la que se puede acceder desde este enlace: <i>https://best.eu.org/student/career/index.jsp</i>.'],
			acceptsCV: false,
		},
		company11: {
			name: 'BBVA',
			icon: '/images/bbva_logo.png',
			description: ['La historia de BBVA es la historia de muchas personas que, desde mediados del siglo XIX, han formado parte de más de un centenar de entidades financieras que se han ido uniendo para ampliar su proyecto empresarial','Hoy, en BBVA trabajamos por un futuro mejor para las personas, buscando relaciones duraderas con nuestros clientes que cambian la forma de ver el negocio. Como resultado de este trabajo, BBVA se ha convertido en todo un referente mundial y en uno de los bancos más reconocidos y premiados.','BBVA apuesta firmemente por el futuro y está siendo pionero en la adaptación a las necesidades que impone un mercado cada vez más global, en definitiva, a la banca del siglo XXI.','Una trayectoria de más de 150 años avala esta apuesta.'],
			profiles: ['Carreras técnicas superiores: Ingenierías, Matemáticas, Estadística, Física, etc','Economía y ADE'],
			link: 'https://careers.bbva.com/espana/',
			hasLink: true,
			acceptsCV: true,
		},
		company12: {
			name: 'B-Lingual',
			icon: '/images/B-lingual_logo.png',
			description: ['Somos una <b>consolidada Agencia Internacional de Au Pairs</b> con oficina central en Madrid, que promociona el intercambio cultural y lingüístico en todo el mundo a través del Programa Au Pair. Más de media década de intermediaciones exitosas nos avala. Disponemos de <b>oficinas en Alemania e Inglaterra</b> y partners de confianza que nos representan en <b>Irlanda, Francia, Polonia, China, Australia y Canada</b> que dan apoyo permanente a nuestros candidatos.','El <b>Programa Au Pair</b> está diseñado para jóvenes a los que les gustan los niños, vivir en familia y que quieren aprender un idioma de manera rápida, segura y económica. Con estancias mínimas de 3 meses(Programa Au Pair de verano), para conseguir un nivel de idioma óptimo, recomendamos estancias de 6-12 meses.','Tras el programa Au Pair, nuestros jóvenes vuelven con su objetivo cumplido: aprender y mejorar un idioma y con el nivel necesario para incorporarse al mercado laboral. Además de experimentar la cultura del país, las vivencias y la experiencia adquirida aportarán al estudiante valiosos valores para su futuro profesional, tales como madurez, independencia, responsabilidad, resolución, etc...','Para más detalles visita:','http://www.b-lingualexperience.com/en050100_programsBIM.html','PERSPECTIVAS DE TRABAJO EN ALEMANIA: EL PROGRAMA AU PAIR COMO PRIMERA ETAPA E INMERSIÓN EN EL PAÍS DE ACOGIDA','El Programa Au Pair os brindará la oportunidad de <B>incorporaros al mercado laboral alemán de una manera segura y cómoda</b>, con una probabilidad de éxito alta y de forma casi inmediata.','En Forum BEST Madrid 2016 impartiremos una conferencia sobre las perspectivas de trabajo en Alemania y el Programa Au Pair como trampolín para acceder a él.','En esta feria, concederemos <b>descuentos</b> a los estudiantes que se registren y <b>sortearemos cursos de alemán intensivo en Frankfurt</b> y muchos premios más.','No dudes en pasarte por nuestro Stand, donde te espera el equipo de B-lingual Experience y Go Pair para informarte sobre nuestros programas.'],
			profiles:['Estudiantes de últimos cursos con interés en aprender un idioma extrajero'],
			link: 'www.b-lingualexperience.com',
			hasLink: true,
			acceptsCV: false,
		},
		company13: {
			name: 'Carrefour',
			icon: '/images/Carrefour_logo.jpg',
			description: ['En la actualidad, contamos con más de <b>470.000 empleados</b> en más de <b>30 países</b>. Somos la empresa <b>nº 1</b> de distribución <b>en Europa</b> y nº 2 en el mundo gracias a la pasión y el talento de nuestros empleados.','Somos de origen Francés y estamos presentes en España desde el año 1973, donde 40.000 personas componemos Carrefour y gestionamos 173 hipermercados, 115 supermercados y 114 tiendas de proximidad. Además, Carrefour cuenta con las líneas de negocio: Finanzas y Seguros, gasolineras, viajes, Carrefour móvil y entradas.','Nuestra ambición es seguir siendo el comerciante favorito <b>¿Cómo lo conseguimos?</b>','Siendo <b>innovadores</b> ofreciendo nuevo productos, apostando por la diversidad de formatos de tienda, incorporando nuevos servicios y para mejorar la vida de <b>nuestros clientes.</b>'],
			profiles:['Ingenieros Agrónomos y Agrícolas','Ingenieros de Telecomunicaciones','Ingenieros Industriales'],
			link: 'http://www.carrefour.es/trabaja-en- carrefour/mas-info/',
			hasLink: true,
			acceptsCV: true,
		},
		company14: {
			name: 'Efron Consulting',
			icon: '/images/efron_logo.png',
			description: ['Efron Consulting es una compañía de Consultoría, Tecnología y Outsourcing, que cuenta en la actualidad con más de 700 profesionales trabajando en proyectos nacionales e internacionales en los Sectores Financiero, Sanitario, Telecomunicaciones, Industria y Administración Pública, con oficinas en España (Madrid y Barcelona), Estados Unidos (Boston), Colombia (Bogotá y Medellín) y México (México DC y Santiago de Querétaro).','CALIDAD E INNOVACIÓN','En Efron promovemos la implantación de una estrategia de actuación para consolidar las buenas prácticas e incrementar la madurez de los servicios de nuestro catálogo, así como el conocimiento y la constante innovación de los servicios ofrecidos a cliente y mirando hacia el futuro diseñando y avanzando las soluciones que demandarán nuestros clientes y el mercado.','EQUIPO HUMANO','Apostamos por el talento y los profesionales y ofrecemos servicios profesionalizados, estandarizados y externalizados que acompañan al software en el camino que realiza, de forma controlada y sin errores.','COMPROMISO','Combinando tecnología, organización y procesos de negocio, apostamos por la especialización para ofrecer valor en un sector de gran competitividad.','Nuestro compromiso es con la eficiencia, la innovación y la calidad.'],
			profiles: ['Ingenieros Informáticos','Ingenieros en sistemas de Telecomunicaciones','Graduados en Ingeniería del Software','Físicos','Matemáticos'],
	link: 'www.efronconsulting.com',
	hasLink: true,
	acceptsCV: true,
},
		company15: {
			name: 'Endesa',
			icon: '/images/endesa_logo.png',
			description: ['QUIÉNES SOMOS:','Endesa es la empresa líder del sector eléctrico español y el segundo operador en el mercado eléctrico portugués. Somos una compañía que mira al futuro y busca soluciones inteligentes para desarrollar propuestas realistas ante los retos energéticos de un sector en continua evolución. Endesa cuenta con más de 10 mil empleados y presta servicio a más de 11 millones de clientes. Desde el primer trimestre de 2009 Endesa forma parte del Grupo Enel, una compañía multinacional del sector de la energía y un operador integrado líder en los mercados mundiales de electricidad y gas, focalizado en los mercados de Europa y Latinoamérica. El Grupo realiza operaciones en 32 países de 4 continentes, gestiona la generación de energía de más de 95 GW de capacidad instalada neta y distribuye electricidad y gas a través de una red que se extiende alrededor de 1,9 millones de kilómetros.','QUÉ BUSCAMOS:','Endesa apuesta por el talento joven y necesita personas como tú:','<li>Ingenieros Industriales, recién graduados, con perfil técnicos y no técnicos.</li><li>Con un alto nivel de inglés</li><li>Personas que encajen con los valores de la compañía, dinámicas, proactivas, innovadoras y responsables. Con un espíritu flexible y con ganas de construir el modelo energético futuro.</li>','Como empresa socialmente responsable queremos ayudar a los jóvenes a incrementar su empleabilidad.','QUÉ OFRECEMOS:','<li>Becas para jóvenes titulados y prácticas para alumnos de últimos cursos de ingeniería.</li>La empresa ofrece 145 becas en las diferentes áreas de negocio de toda España. Con una duración de un año, jornada completa, ayuda económica mensual que te permitirá conseguir un continuo desarrollo personal y profesional dentro de la compañía.'],
			profiles: ['Ingenieros Industriales','Grado en Informática','Grado en Matemáticas','Grado en Estadística','Grado en Física','Grado en Económicas','Grado en ADE','Grado en Derecho'],
			link:'www.endesa.com',
			hasLink: true,
			acceptsCV: true,
		},
		company16: {
			name: 'EOI: Escuela de Organización Industrial',
			icon: '/images/eoi_logo.jpg',
			description: ['Quiénes somos:', 'Te presentamos nuestra Escuela y nuestros programas máster para recién titulados. Llevamos 60 años formando a personas que hoy están ocupando puestos de responsabilidad en multinacionales, empresas, asociaciones… y seguimos evolucionando con unos programas adaptados a tus necesidades y a las necesidades de las empresas con las que trabajarás.', 'Qué buscamos:', 'Buscamos a los directivos y gestores de empresas del mañana. Se acerca el momento en el que cerrarás con éxito otra etapa, tu etapa universitaria. Y no podemos más que felicitarte: ¡¡enhorabuena!!', '¿Has pensado qué hacer después?', '¿Has pensado qué hacer ahora?', 'Qué ofrecemos:', 'Ofrecemos una formación de postgrado adecuada a tus necesidades, desde programas líderes en Gestión Empresarial hasta programas altamente especializados en Medioambiente y Sostenibilidad, en su modalidad presencial u online y siempre con las metodologías de trabajo más innovadoras.', 'Una formación que está:', 'CERCA DE LA EMPRESA', 'Nuestros programas se adaptan constantemente a las necesidades de las empresas. Queremos que aprendas exactamente lo que necesitarás en tu puesto de trabajo.', 'CERCA DEL MUNDO', 'Contamos con profesores visitantes internacionales que, junto con tus propios compañeros procedentes de muy diversos países, te sumergirán en un aprendizaje global. Nuestros postgrados cuentan con un study tryp y te damos la oportunidad de realizar algunos de nuestros másters íntegramente en inglés o, si lo prefieres, algunas asignaturas.', 'CERCA DE TI', '» Cuando termines tu máster de postgrado, te ofrecemos la posibilidad de realizar prácticas remuneradas en importantes empresas. ¿Qué mejor forma de entrar en el mercado laboral?', '» Podrás acceder a una exclusiva bolsa de empleo, a través de nuestro servicio de Carreras Profesionales, que colabora más de 2.000 empresas.', '» Sabemos que plantearte seguir estudiando implica un fuerte esfuerzo económico. Precisamente porque creemos que el dinero no debe condicionar tu futuro presente, ponemos a tu disposición un amplio programa de becas y ayudas económicas.'],
			profiles: ['Todo tipo de perfiles'],
			link:'www.eoi.es',
			hasLink: true,
			acceptsCV: false,
		},
		company17: {
			name: 'EY',
			icon: '/images/ey_logo.png',
			description: ['EY es líder mundial en servicios de auditoría, fiscalidad, asesoramiento en transacciones y consultoría, con más de 190.000 profesionales en más de 150 países. Nuestro lema, “Building a better working world”, consiste en contribuir a construir un entorno mejor en todos nuestros ámbitos de actuación y ser relevantes para nuestros clientes.','La Firma tiene una estrategia conocida como Visión 2020, cuyo objetivo es impactar en los valores y la calidad de nuestro trabajo. Gira entorno a tres pilares: ser relevantes para el mercado, potenciar los equipos de alto rendimiento y apostar en sinergias globales para reforzar el entorno local. Todo esto nos permitirá dar un servicio excepcional a nuestros clientes.'],
			profiles: ['Nuestras ofertas están dirigidas a Titulados o estudiantes de último curso de Derecho, Administración y Dirección de Empresas, Dobles Titulaciones, Ciencias Económicas, Ciencias Actuariales y Financieras, Matemáticas, Estadística, Ingenierías Informáticas, Industriales o de Telecomunicaciones, con alto nivel de inglés, capacidad de liderazgo, integridad, pasión e iniciativa y motivados por formar parte de un equipo de profesionales innovador y dinámico, capaz de ofrecer a las empresas soluciones de éxito para unos mercados cada vez más globales.'],
			link:'www.ey.com/es',
			hasLink: true,
			acceptsCV: true,
		},
		company18: {
			name: 'GMV',
			icon: '/images/gmv_logo.jpg',
			description: ['NUESTRO OBJETIVO', 'Nuestro propósito es apoyar los procesos de nuestros clientes a través de soluciones tecnológicamente avanzadas proporcionando sistemas integrados, productos y servicios especializados que cubren todo el ciclo de vida. Desde servicios de consultoría e ingeniería, hasta el desarrollo de software y hardware, integración de sistemas llave en mano y soporte a las operaciones con un compromiso total con la calidad y la competitividad.', '¿QUÉ OFRECEMOS?', 'Desde la incorporación, nuestros jóvenes profesionales tienen la oportunidad de abordar retos tecnológicos en un entorno innovador, desarrollar su trabajo en equipos multidisciplinares y tener un trato directo con los clientes, lo que les permite adquirir una gran madurez profesional.', 'Existe la posibilidad de desarrollar esta actividad fuera de España, trabajando en nuestros centros en el extranjero o en las instalaciones de nuestros clientes (Alemania, Francia, Italia, Holanda...).', 'Ofrecemos una formación permanente que permite a nuestros profesionales mantenerse en la punta de lanza de las tecnologías utilizadas.', 'PROCESO DE SELECCIÓN', 'El proceso de selección de GMV se basa tanto en las capacidades aportadas como en una aptitud volcada hacia la tecnología y el trabajo en equipo. Las actividades tecnológicas de GMV requieren titulados en Ingeniería Aeronáutica, Telecomunicación, Informática, Industrial, Licenciaturas en CC. Físicas, Matemáticas. Nuestra proyección internacional hace necesario un nivel alto de inglés, valorándose el conocimiento de otros idiomas.'],
			profiles: ['Las actividades tecnológicas de GMV requieren titulados en Ingeniería Aeronáutica, Telecomunicación, Informática, Industrial, Licenciaturas en CC. Físicas, Matemáticas.'],
			banner: ['<img src="images/gmv_banner.jpg" alt="Smiley face" width="600"/>'],
			link: 'http://www.gmv.com/',
			hasLink: true,
			acceptsCV: true,
		},
		company19: {
			name: 'Indra',
			icon: '/images/indra_logo.jpg',
			description: ['40.000 profesionales de consultoría y tecnología', 'Un lugar para ti', 'Trae tu talento a una compañía global de consultoría y tecnología, con presencia en los 5 continentes y 40.000 profesionales. Trabajarás en un entorno de soluciones y servicios innovadores para nuestro clientes en los principales sectores de actividad, aportándoles valor añadido. Participarás de la transformación de los negocios trabajando con profesionales de referencia.', 'Una carrera profesional y personal de éxito', 'En Indra tendrás una carrera profesional adaptada a tus objetivos personales, con formación continua y en un entorno flexible. Participarás en proyectos internacionales, con equipos multiculturales o locales, según tus preferencias, en un entorno diverso y con igualdad de oportunidades. Disfrutarás de numerosos beneficios sociales y un interesante paquete retributivo, al tiempo que creces en un entorno innovador.', 'Transformamos el mundo a través de la tecnología y la innovación. ¡Ven a descubrirlo!'],
			profiles: ['Grados en Informática, Matemáticas, Físicas, Ingeniería Industrial y Telecomunicaciones'],
			link: 'http://www.indraempleo.com/',
			hasLink: true,
			acceptsCV: true,
		},
		company20: {
			name: 'IE BUSINESS SCHOOL',
			icon: '/images/IE_logo.jpg',
			description: ['IE es una de las instituciones educativas más reconocidas internacionalmente, siendo considerada la primera escuela de España por Financial Times en 2015. Pionera en la educación empresarial, IE educa a los líderes del futuro, promoviendo los valores de espíritu emprendedor, diversidad, innovación y responsabilidad social.', 'El campus de IE se encuentra en el centro de Madrid, brindando a los alumnos la oportunidad de aprovechar todo lo que la ciudad tiene que ofrecer. Además, en cualquier momento del año conviven en el campus alumnos de más de 90 nacionalidades.', 'En IE se imparten un número de programas tanto a tiempo completo, como a tiempo parcial, para jóvenes con talento, profesionales y ejecutivos. Nuestro portfolio de programas incluye el Master in Management, Masters en Finanzas, y MBAs. Además se ofrecen programas especializados de sus distintas escuelas: IE Business School, IE Law School, IE School of International Relations, IE School of Human Sciences &amp; Technology e IE Scool of Architecture and Design.'],
			profiles: ['IE realiza una selección rigurosa entre el gran número de solicitudes que solicitan su admisión, seleccionando candidatos dinámicos, motivados, creativos, con un alto potencial, que no sólo destaquen por su perfil académico y profesional, sino también por sus habilidades interpersonales que les permitan obtener un máximo aprovechamiento del programa.'],
			link: 'http://www.ie.edu/',
			hasLink: true,
			acceptsCV: true,
		},
		company21: {
			name: 'LID Editorial',
			icon: '/images/LID_logo.jpg',
			description: ['LID Editorial, fundada en 1993, es un grupo empresarial líder en la creación y difusión de contenidos de empresa en diferentes formatos.', 'Publicamos libros en formato impreso y digital, editamos revistas académicas y profesionales, gestionamos una red de conferenciantes y una plataforma de formación online pionera en transformación digital (LIDlearning) y somos parte de Bluebottlebiz, la primera plataforma colaborativa de aprendizaje online con los mejores contenidos de empresa a nivel internacional.', 'LID Editorial cuenta con sedes en Madrid, Barcelona, Monterrey, México D.F., Bogotá, Buenos Aires, Shanghái, Londres, Nueva York y San Francisco.', 'LIDlearning es el servicio de formación online de LID Editorial, orientado a proporcionar a las empresas las competencias especializadas en transformación digital e innovación. Gestionamos los mejores contenidos de elearning de mano de los más destacados expertos en las nuevas tendencias tecnológicas. Cursos de empresa, prácticos y de calidad para la mejora personal y profesional.'],
			profiles: ['Todos los perfiles.'],
			link: 'http://www.lideditorial.com/',
			hasLink: true,
			acceptsCV: true,
		},
		company22: {
			name: 'Oficina Española de Patentes y Marcas',
			icon: '/images/oepm_logo.png',
			description: ['La Oficina Española de Patentes y Marcas (OEPM) es un Organismo Autónomo del Ministerio de Industria, Energía y Turismo que impulsa y apoya el desarrollo tecnológico y económico otorgando protección jurídica a las distintas modalidades de propiedad industrial mediante la concesión de patentes y modelos de utilidad (invenciones); diseños industriales (creaciones de forma); marcas y nombres comerciales (signos distintivos) y títulos de protección de las topografías de productos semiconductores. Asimismo, difunde la información relativa a las diferentes formas de protección de la propiedad industrial.'],
			link: 'http://www.oepm.es/es/index.html',
			hasLink: true,
			acceptsCV: true,
		},
		company23: {
			name: 'Orange',
			icon: '/images/orange_logo.png',
			description: ['España es el segundo mercado del Grupo Orange, uno de los principales operadores de telecomunicaciones del mundo con 263 millones de clientes en la actualidad.', 'Con un proyecto de generación de valor basado en la convergencia, la innovación y la calidad de servicio, tienen la ambición de ser el operador alternativo de referencia en el mercado español telecomunicaciones, donde ya son uno de los principales inversores extranjeros, con más de 20.000 millones de euros de inversión acumulada.', 'A través de sus distintas marcas Orange, Jazztel, así como Amena y Simyo en el segmento de bajo coste, cuentan hoy con la confianza de cerca de 18,9 millones de clientes (15,2 millones clientes móviles y y 3,7 millones de banda ancha fija), que disfrutan de sus servicios fijos, móviles y de televisión, a 30 de septiembre de 2015.', 'Su misión, reflejada en el plan estratégico Esenciales 2020 es conectar a todos - personas, familias, empresas...- con lo que es y será fundamental en sus vidas. En definitiva, como indica el leit motive, en Orange "te acercamos a lo que te importa".'],
			profiles: ['Ingeniería de Telecomunicaciones, Informática, Industrial, ADE, Marketing, Finanzas, Derecho, Recursos Humanos, Investigación de mercados, Economía y Periodismo', 'Envío de CVs: http:\\becas.orange.es'],
			link: 'http://www.orange.com/es/home',
			hasLink: true,
			acceptsCV: true,
		},

		company24: {
			name: 'OVB Allfinanz España, S.A.',
			icon: '/images/OVB_logo.png',
			description: ['OVB, compañía líder en asesoramiento financiero en Europa. Desde su fundación en 1970 en Colonia, Alemania, hasta el día de hoy, nuestra preocupación por los objetivos y necesidades de nuestros clientes, nos ha llevado a 14 países en Europa, entre ellos España en 2003','El grupo OVB cotiza en la Bolsa de Frankfurt desde Julio de 2006 y colabora con más de 150 entidades de gran renombre y alta competitividad en el sector financiero y asegurador, tanto a nivel nacional como internacional.','OVB Allfinanz España trabaja, como en el resto de Europa, con el método A-A-S (Análisis, Asesoramiento y Servicio) que se orienta en las fases de la vida, considerando los factores que influyen como la edad, el entorno profesional y social, las prioridades y deseos de cada uno.','Tanto los objetivos a corto como a largo plazo se tienen en cuenta en nuestro modelo de asesoramiento de manera que realmente sea posible planificar eficazmente el futuro y acompañar al cliente prestando nuestro servicio a lo largo de toda la vida.','OVB Allfinanz España no tiene productos propios, por tanto nuestro asesoramiento es independiente y personalizado para el cliente con un servicio dinámico y continuo.','Nuestros 3 millones de clientes agradecen haber encontrado en el asesoramiento multitemático de OVB un servicio individualizado que les da respuesta a todas sus cuestiones y dudas financieras.','El asesoramiento multitemático de OVB Allfinanz España se divide en las siguientes fases:','<li>Protección personal y de ingresos, asegurando que nuestro cliente siempre alcance sus objetivos.</li><li>Protección del patrimonio, garantizando la seguridad del mismo.</li><li>Protección del patrimonio, garantizando la seguridad del mismo.</li><li>Creación del patrimonio, destinado a construir un patrimonio para la jubilación.</li><li>Crecimiento del patrimonio, optimizando la elección de nuestro cliente.</li>','El cumplimiento de todas las fases del asesoramiento multitemático de OVB Allfinanz España tendrá como resultado una correcta planificación financiera para nuestro cliente.','Visítanos en:'],
			link:'www.ovb.es',
			hasLink: true,
			acceptsCV: true,
		},
		company25: {
			name: 'Page Personnel',
			icon: '/images/pagepersonnel_logo.jpg',
			description: ['Page Personnel, perteneciente a PageGroup, es la consultora líder en selección y trabajo temporal especializado. Identificamos y seleccionamos perfiles intermedios y personal de apoyo cualificado para posiciones temporales e indefinidas a través de nuestros consultores especializados. Nuestra misión es satisfacer las necesidades de selección de nuestros clientes y ayudar en el desarrollo profesional de nuestros candidatos.','Estamos especializados en 15 áreas, entre ellas destacamos Tecnologías de la información e Ingenieros y Técnicos. Los perfiles más habituales que cubrimos en el área tecnológica son:',' <li>Desarrolladores</li> <li>Jefaturas de Proyecto</li><li>Administradores de sistemas</li><li>Expertos en BBDD</li>','Dentro del área ingenieril, nuestros posiciones suelen ser:','<li>Supply Chain: Logística, compras y almacén</li><li>Oficina Técnica: Estudios, presupuestos, I+D y proyectos</li><li>Procesos: Mantenimiento, calidad y producción</li>','Visítanos en:'],
			link:'www.pagepersonnel.es',
			video:'https://www.youtube.com/watch?v=itCyUfV4EiA',
			hasLink: true,
			acceptsCV: true,
		},
		company26: {
			name: 'Profco - Mediación de personal de enfermería para trabajar en Alemania.',
			icon: '/images/profco_logo.png',
			description: ['Profco es la agencia de mediación personal en la atención sanitaria. Nuestra tarea es integrar profesionales de enfermería graduados españoles en empresas alemanas en el sector de hospitales, clínicas, residencias geriátricas y otras instituciones. Hemos desarrollado un concepto totalmente nuevo que ha sido estudiado y examinado con detenimiento por la Red EURES (European Employment Service) y otras instituciones como por ejemplo la Red iQ de Alemania.','Nuestro proyecto incluye sin coste alguno para los candidatos:','<li>Preparación hasta alcanzar el nivel requerido de alemán (B2 – de acuerdo con el marco europeo de referencia).</li><li>Gestiones necesarias para la homologación del título.</li><li>Mediación, acompañamiento y supervisión para formalizar el contrato de trabajo entre la empresa (hospital, clínica, residencia, etc.) y el trabajador (enfermero/a).</li><li>Ayuda para encontrar vivienda en Alemania.</li><li>Asistencia y apoyo después de la incorporación al puesto de trabajo.</li>','Requisitos mínimos:','<li>Título de enfermería.</li><li>Los/as solicitantes deben aportar comprobantes de seguros españoles que tengan una validez de tres meses después de su llegada a Alemania (en particular seguro médico, de accidentes y de responsabilidad civil).</li><li>Comprensión y la habilidad para adaptarse a otras personas</li><li>Responsabilidad y aptitud para el trabajo en equipo.</li>','Procedimiento:','<li>Selección de candidatos por profesionales de profco.</li><li>Curso intensivo de alemán hasta alcanzar el nivel B2 (en España y Alemania).</li><li>Entrevistas de trabajo con posibles empleadores.</li><li>Acompañamiento constante hasta firmar el contrato y después apoyo durante 2 años por un gestor de proyecto que habla español</li><li>Apoyo para resolver diversos trámites burocráticos (dar de alta el domicilio, solicitar tarjeta fiscal, abrir una cuenta bancaria, dar de alta un vehículo, contratar una línea de Internet y teléfono, etc.)</li><li>Asistencia durante el proceso de incorporación</li>','Franja salarial:','<li>A partir de 30.000€ en clínicas y residencias geriátricas.</li>','Con profco de la mano, la integración es más fácil.','Visítanos en:'],
			link:'www.profco.de',
			hasLink: true,
			acceptsCV: true,
		},
		company27: {
			name: 'RSI y Nessa Global Banking Solutions (Grupo Caja Rural)',
			icon: '/images/rsi_logo.jpg',
			description: ['Desde 1987 RSI ha sido gran referente de la tecnología bancaria. RSI nace de la innovación y de la actualidad tecnológica con el fin de dar el mejor servicio a las entidades financieras que confían en nosotros: tanto en nuestro equipo como en nuestras aplicaciones. Hoy en día este panorama tecnológico se instala en el sector bancario a través de nuevas metodologías como e-baking o banca digital y la necesidad de nuestras soluciones cada día son más demandadas en el sector.  La calidad, el trabajo en equipo, así como la formación constante son los pilares de nuestro negocio. El valor fresco, joven y dinámico es el motor de nuestra experiencia y sobre todo son requisitos esenciales para RSI. Necesitamos tu empuje y vivacidad. RSI quiere ser el comienzo de tu trayectoria profesional.',' Déjanos tu CV en nuestro stand o escríbenos a <a href="mailto:rrhh_rsi@cajarural.com">rrhh_rsi@cajarural.com</a>','Visítanos en:'],
			link:'http://www.ruralserviciosinformaticos.com/',
			hasLink: true,
			acceptsCV: true,
			banner: ['<img src="images/rsi_banner.jpg" width="600">']
		},
		company28: {
			name: 'RÜCKER LYPSA, SLU ( EDAG Group )',
			icon: '/images/rueckerlypsa_logo.jpg',
			description: ['DESCRIPCIÓN:','As a leading global independent engineering partner for the international mobility industry, the EDAG Group, to which the Rücker Lypsa have also belonged since the beginning of the year 2014, develops ready-for-production solutions for automotive future. The industry focus is on the automotive and commercial vehicle industry.','The development of vehicles, derivates, modules and production plant is part of the service portfolio. The EDAG Group is organised into the lines of business Vehicle Engineering, Production Solutions and Electric/Electronics. Vehicle Engineering offers global engineering services and know-how along the entire automotive development process focusing on the manufacturers and suppliers of the automotive industry. The service portfolio covers the key aspects of vehicle development and ranges from styling, form-finding and modelling through package, body and interior/exterior design development to the entire functional integration of systems into the vehicle.','Production Solutions deals with the development of production facilities and factory concepts. The focus is on factory, process and plant development as well as automation engineering and product cost management.','<b>Rücker Lypsa S.L.U.</b>( currently employing more tan 500 professionals ) is the center of competence for styling, design and models of the whole group and is also leader in the Spanish market in design, engineering in powertrain, body and trim development as well as electric / electronic development ( vehicle electric/electronics, comfort and body electronics, driver assistance and safety systems, infotainment and telematics systems as well as electric/electronic system ).','Visit us in:'],
			link:'www.rueckerlypsa.es',
			hasLink: true,
			acceptsCV: true,

		},
		company29: {
			name: 'SCHNEIDER ELECTRIC',
			icon: '/images/schneider_logo.png',
			description: ['DESCRIPCIÓN:','Schneider Electric, como especialista global en gestión de la energía y con operaciones en más de 100 países, ofrece soluciones integrales para diferentes segmentos de mercado, ostentando posiciones de liderazgo en energía e infraestructuras, industria, edificios y centros de datos, así como una amplia presencia en el sector residencial. ','Hoy los más de 170.000 trabajadores de Schneider, gracias a su experiencia ofrecen soluciones innovadoras a nuestros clientes en más de 100 países. Gracias a nuestro programa de acceso a la energía, hemos hecho posible que 2,4 millones de personas dispongan de energía. Es lo que denominamos LIFE IS ON.','Ofrecemos la oportunidad de adherirse a una Compañía internacional, dinámica y responsable que promueve el desarrollo de toda su gente y comunidades de todo el mundo. Siempre fomentando la diversidad e inclusión.','Los valores son el fundamento más sólido para garantizar el éxito a largo plazo de las compañías y favorecer una cultura abierta, de confianza mutua y sostenible. Creemos que una compañía con fuertes valores puede marcar la diferencia en nuestra sociedad.','En Schneider Electric queremos marcar la diferencia todos y cada uno de los días. Por eso trabajamos para que nuestros 8 principios hagan de Schneider Electric una gran compañía.','Visítanos en:'],
			link:'http://www.schneider-electric.es/es/',
			video:'https://www.youtube.com/watch?v=5F17ixk2UUQ',
			hasLink: true,
			acceptsCV: true,
			banner: ['<img src="images/Schneider_banner.jpg" width="600">']
		},
	},
	SCHOOLS: {
		etsi_aeronautica_y_del_espacio : 'ETSI Aeronaútica y del Espacio',
    etsi_montes_forestal_y_del_medio_natural : 'ETSI Montes, Forestal y del Medio Natural',
    ets_de_arquitectura : 'ETS de Arquitectura',
    etsi_aeronauticos : 'ETSI Aeronáuticos',
    etsi_agronomos : 'ETSI Agrónomos',
    etsi_caminos_canales_y_puertos : 'ETSI Caminos, Canales y Puertos',
    etsi_montes : 'ETSI Montes',
    etsi_navales : 'ETSI Navales',
    etsi_telecomunicacion : 'ETSI Telecomunicación',
    facultad_de_ciencias_de_la_actividad_fisica_y_del_deporte_inef : 'Facultad de Ciencias de la Actividad Física y del Deporte (INEF)',
    ets_de_edificacion : 'ETS de Edificación',
    euit_aeronautica : 'EUIT Aeronáutica',
    euit_agricola : 'EUIT Agrícola',
    euit_forestal : 'EUIT Forestal',
    centro_de_investigacion_del_transporte_transyt : 'Centro de Investigación del Transporte (TRANSyT)',
    centro_de_estudios_e_inv_para_la_gestion_de_riesgos_agrarios_y_medioamb : 'Centro de Estudios e Inv. para la Gestión de Riesgos Agrarios y Medioamb.',
    instituto_de_sistemas_optoelectronicos_y_microtecnologia : 'Instituto de Sistemas Optoelectrónicos y Microtecnología',
    instituto_de_energia_solar : 'Instituto de Energía Solar',
    instituto_de_ciencias_de_la_educacion_ice : 'Instituto de Ciencias de la Educación (ICE)',
    centro_de_materiales_y_dispositivos_avanzados_para_tic_cemdatic : 'Centro de Materiales y Dispositivos Avanzados para TIC (CEMDATIC)',
    etsi_industriales : 'ETSI Industriales',
    etsi_de_minas_y_energia : 'ETSI de Minas y Energía',
    etsi_diseno_industrial : 'ETSI Diseño Industrial',
    etsi_civil : 'ETSI Civil',
    centro_de_electronica_industrial_cei : 'Centro de Electrónica Industrial (CEI)',
    instituto_de_fusion_nuclear : 'Instituto de Fusión Nuclear',
    centro_de_automatica_y_robotica_car_centro_mixto_upm_csic : 'Centro de Automática y Robótica (CAR). Centro Mixto UPM-CSIC',
    ets_de_ingenieros_informaticos : 'ETS de Ingenieros Informáticos',
    centro_domotica_integral_cedint : 'Centro domótica Integral (CEDINT)',
    centro_de_inv_en_biotecnologia_y_genomica_de_plantas_cbgp : 'Centro de Inv. en Biotecnología y Genómica de Plantas (CBGP)',
    insituto_de_microgravedad_ignacio_da_riva : 'Insituto de Microgravedad "Ignacio Da Riva"',
    e_usoc : 'E-USOC',
    cesvima : 'CESVIMA',
    etsi_en_topografia_geodesia_y_cartografia : 'ETSI en Topografía, Geodesia y Cartografía',
    etsi_de_sistemas_informaticos : 'ETSI de Sistemas Informáticos',
    etsi_y_sistemas_de_telecomunicacion : 'ETSI y Sistemas de Telecomunicación',
    centro_laser : 'Centro Láser',
    instituto_de_investigacion_del_automovil : 'Instituto de Investigación del Automóvil',
    centro_de_investigacion_en_tecnologias_del_sw_y_sist_multimedia_citsem : 'Centro de Investigación en Tecnologías del SW y Sist. Multimedia (CITSEM)',
    centro_superior_de_diseno_de_moda_de_madrid : 'Centro Superior de Diseño de Moda de Madrid',
    facultad_de_bellas_artes : 'Facultad de Bellas Artes',
    facultad_de_ciencias_biologicas : 'Facultad de Ciencias Biológicas',
    facultad_de_ciencias_de_la_documentacion : 'Facultad de Ciencias de la Documentación',
    facultad_de_ciencias_de_la_informacion : 'Facultad de Ciencias de la Información',
    facultad_de_ciencias_economicas_y_empresariales : 'Facultad de Ciencias Económicas y Empresariales',
    facultad_de_ciencias_fisicas : 'Facultad de Ciencias Físicas',
    facultad_de_ciencias_geologicas : 'Facultad de Ciencias Geológicas',
    facultad_de_ciencias_matematicas : 'Facultad de Ciencias Matemáticas',
    facultad_de_ciencias_politicas_y_sociologia : 'Facultad de Ciencias Políticas y Sociología',
    facultad_de_ciencias_quimicas : 'Facultad de Ciencias Químicas',
    facultad_de_comercio_y_turismo : 'Facultad de Comercio y Turismo',
    facultad_de_derecho : 'Facultad de Derecho',
    facultad_de_educacion_centro_de_formacion_del_profesorado : 'Facultad de Educación - Centro de Formación del Profesorado',
    facultad_de_enfermeria_fisioterapia_y_podologia : 'Facultad de Enfermería, Fisioterapia y Podología',
    facultad_de_estudios_estadisticos : 'Facultad de Estudios Estadísticos',
    facultad_de_farmacia : 'Facultad de Farmacia',
    facultad_de_filologia : 'Facultad de Filología',
    facultad_de_filosofia : 'Facultad de Filosofía',
    facultad_de_geografia_e_historia : 'Facultad de Geografía e Historia',
    facultad_de_informatica : 'Facultad de Informática',
    facultad_de_medicina : 'Facultad de Medicina',
    facultad_de_odontologia : 'Facultad de Odontología',
    facultad_de_optica_y_optometria : 'Facultad de óptica y Optometría',
    facultad_de_psicologia : 'Facultad de Psicología',
    facultad_de_trabajo_social : 'Facultad de Trabajo Social',
    facultad_de_veterinaria : 'Facultad de Veterinaria',
    otros_centros : 'Otros Centros',
	}
};
$(document).ready(function(){
	// the "href" attribute of .modal-trigger must specify the modal ID that wants to be triggered
	$('.modal-trigger').leanModal();
});
